"""empty message

Revision ID: f9e06a211a40
Revises: 
Create Date: 2019-07-27 13:54:10.454353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e06a211a40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_created_at', sa.DateTime(), nullable=False),
    sa.Column('payment_id', sa.String(length=128), nullable=True),
    sa.Column('order_id', sa.String(length=10), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=True),
    sa.Column('total_parts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'part', name='_paymentid_part_uc')
    )
    op.create_index(op.f('ix_order_payment_id'), 'order', ['payment_id'], unique=True)
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('_modifiers', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_index(op.f('ix_order_payment_id'), table_name='order')
    op.drop_table('order')
    op.drop_table('last_run')
    # ### end Alembic commands ###
